# Generated by Django 4.1.2 on 2022-12-14 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0003_mensajes_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensajes',
        ),
    ]
