# Generated by Django 4.1.2 on 2022-12-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0005_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['timestamp']},
        ),
    ]
