# Generated by Django 4.1.2 on 2022-12-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAirsoft', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
