# Generated by Django 4.1.2 on 2022-12-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAirsoft', '0003_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipamiento'),
        ),
        migrations.AddField(
            model_name='replica',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='replicas'),
        ),
    ]
