# Generated by Django 4.1.2 on 2022-12-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAirsoft', '0004_equipamiento_imagen_replica_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_promo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
