# Generated by Django 4.1.2 on 2022-12-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAirsoft', '0005_promos'),
    ]

    operations = [
        migrations.AddField(
            model_name='promos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='replicas'),
        ),
    ]
